#!/bin/bash
set -euo pipefail

# Identify missing tools that should have governance packages

echo "🔍 Analyzing current governance packages and identifying missing tools..."

# Current tools covered
echo "✅ Currently covered tools:"
echo "  - npm (Node.js package manager)"
echo "  - pnpm (Node.js package manager)"  
echo "  - yarn (Node.js package manager)"
echo "  - bun (JavaScript runtime and package manager)"
echo "  - pip (Python package manager)"
echo "  - curl (HTTP client)"
echo "  - node (JavaScript runtime)"

echo ""
echo "🤔 Missing tools that should have governance:"

echo ""
echo "📦 Package Managers:"
echo "  - cargo (Rust package manager) → prefer alternative build systems"
echo "  - gem (Ruby package manager) → prefer bundler"
echo "  - composer (PHP package manager) → prefer alternative"
echo "  - maven/gradle (Java package managers) → prefer alternative"
echo "  - go mod (Go module manager) → prefer alternative"
echo "  - nuget (dotnet package manager) → prefer alternative"

echo ""
echo "🔧 Build Tools:"
echo "  - make (build tool) → prefer just/ninja"
echo "  - cmake (build system) → prefer alternatives"
echo "  - gcc/clang (compilers) → prefer alternatives for certain use cases"
echo "  - docker (container tool) → prefer podman"

echo ""
echo "🌐 Network Tools:"
echo "  - wget (HTTP client) → prefer curl"
echo "  - ssh (remote shell) → prefer alternatives"
echo "  - rsync (file sync) → prefer alternatives"

echo ""
echo "🐚 Shell Tools:"
echo "  - python (runtime) → prefer specific versions"
echo "  - ruby (runtime) → prefer specific versions"
echo "  - node (runtime) → prefer specific versions"
echo "  - java (runtime) → prefer specific versions"

echo ""
echo "📋 Priority assessment:"
echo "  🚀 High Priority (immediate need):"
echo "    - cargo → prefer alternative build systems"
echo "    - wget → prefer curl"
echo "    - make → prefer just"
echo "    - python → prefer python3/uv"
echo "    - gem → prefer bundler"
echo ""
echo "  🔶 Medium Priority (good to have):"
echo "    - docker → prefer podman"
echo "    - rsync → prefer alternatives"
echo "    - cmake → prefer alternatives"
echo ""
echo "  🔹 Low Priority (specialized):"
echo "    - composer, maven, gradle, go mod, nuget"
echo "    - gcc/clang alternatives"
echo "    - ssh alternatives"

echo ""
echo "📊 Recommended next additions (High Priority):"
echo "1. cargo governance (Rust ecosystem)"
echo "2. wget governance (prefer curl)"  
echo "3. make governance (prefer just)"
echo "4. python governance (prefer python3/uv)"
echo "5. gem governance (prefer bundler)"

echo ""
echo "🎯 Implementation strategy:"
echo "- Start with high-priority tools that have clear alternatives"
echo "- Each new tool follows the same 4-behavior pattern (prefer/eject/force/block)"
echo "- Bundle packages should be updated to include new tools"
echo "- Cross-ecosystem packaging generators need updates"
